### ISSUE TITLE
Скажите пожалуйста что я делаю не верно?

### ISSUE THREAD

**Issue by lp85d** [delphinpro/oscp#2]
D:\OSPanel>osp version
Информация о версии: Open Server Panel v6.0.0.570 x64 04.01.2024 5:06:04

Warning: require_once(D:\OSPanel\home\system/data.php): Failed to open stream: No such file or directory in D:\OSPanel\home\system\index.php on line 19

Fatal error: Uncaught Error: Failed opening required 'D:\OSPanel\home\system/data.php' (include_path='.;D:/OSPanel/data/PHP-8.1/default/composer') in D:\OSPanel\home\system\index.php:19 Stack trace: #0 {main} thrown in D:\OSPanel\home\system\index.php on line 19

**Comment by lp85d** [comment]
![Screenshot 2024-01-19 193321](https://github.com/delphinpro/oscp/assets/3320759/25f766d2-a0b0-4692-a794-70b9fdc86214)

**Comment by lp85d** [comment]
Ну так вот в чём была проблема
Заменяем содержимое архива 
Это D:\user\Downloads\oscp-master.zip\oscp-master\config\ControlPanel\default\
Сюда D:\OSPanel\config\ControlPanel\default
Это D:\user\Downloads\oscp-master.zip\oscp-master\system\public_html\
Сюда D:\OSPanel\system\public_html
Затем запустим сервер после чего заполним
D:\OSPanel\config\domains.ini
```
[api.ospanel]
aliases              =
enabled              = on
engine               = PHP-8.1
ip                   = auto
log_format           = combined
cgi_dir              = {root_dir}\system\cgi-bin
public_dir           = {root_dir}\system\public_html
auto_configure       = on
ssl                  = off
ssl_cert_file        = {root_dir}\user\ssl\default\cert.crt
ssl_key_file         = {root_dir}\user\ssl\default\cert.key
project_home_dir     =
project_add_modules  =
project_add_commands =

```
Перезагрузим сервер и готово
![image](https://github.com/delphinpro/oscp/assets/3320759/837b54ca-5923-4e22-8986-be6f83e961b7)

**Comment by delphinpro** [comment]
Именно это и написано в Readme этого репозитория =))

**Comment by lp85d** [comment]
Интерфейс данного приложения отобразится по адресу указанному в файле D:\OSPanel\config\program.ini api_ip
